const KEY='shiguang-reviews-v1', DRAFT_KEY='shiguang-draft-v1', SETTINGS='shiguang-reminder-v1';
const qualities=['勇气','理性','纯粹','兴趣','情商','专注自我'];
const prompts=['今天，你有没有做一件让自己更像自己的事？','哪一个瞬间让你感到自己正在成长？','今天的你，在哪个时刻最接近真实？','如果重来一次，你会保留哪个选择？','有什么小事，让你重新获得了能量？'];
const $=id=>document.getElementById(id), fields=['event','mindset','method','angle','journey','thinking','lesson'];
let entries=read(KEY), selectedTags=[], currentPrompt=0, dirty=false, lastDate='', editingId=null, activeDateFilter=localDate(), activeTagFilter='全部', viewMonth=new Date();
function read(key){try{return JSON.parse(localStorage.getItem(key)||'[]')}catch{return[]}}
function localDate(d=new Date()){const z=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}`}
function prettyDate(value){const d=new Date(`${value}T12:00:00`);return {day:String(d.getDate()).padStart(2,'0'),month:`${d.getMonth()+1}月`,week:['日','一','二','三','四','五','六'][d.getDay()]}}
function escapeHTML(s=''){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function setTodayLabel(){const d=new Date();$('todayDay').textContent=String(d.getDate()).padStart(2,'0');$('todayMonth').textContent=`${d.getFullYear()} / ${String(d.getMonth()+1).padStart(2,'0')}`}
function renderCalendar(){const y=viewMonth.getFullYear(),m=viewMonth.getMonth();$('calendarMonth').textContent=`${y}年 ${m+1}月`;const first=(new Date(y,m,1).getDay()+6)%7,last=new Date(y,m+1,0).getDate(),prevLast=new Date(y,m,0).getDate(),days=[];for(let i=first-1;i>=0;i--)days.push({day:prevLast-i,muted:true,date:''});for(let d=1;d<=last;d++){const date=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`;days.push({day:d,date})}while(days.length<42){const d=days.length-last-first+1;days.push({day:d,muted:true,date:''})}const entryDates=new Set(entries.map(e=>e.date));$('calendarDays').innerHTML=days.map(x=>`<button type="button" class="calendar-day ${x.muted?'muted ':''}${x.date&&x.date===activeDateFilter?'selected ':''}${x.date===localDate()?'today ':''}${x.date&&entryDates.has(x.date)?'has-entry':''}" ${x.date?`data-date="${x.date}"`:''}>${x.day}</button>`).join('');$('calendarDays').querySelectorAll('[data-date]').forEach(b=>b.addEventListener('click',()=>selectDate(b.dataset.date)))}
function selectDate(next){if(dirty&&!confirm('这篇复盘还没有收好，要放弃当前内容吗？')){$('entryDate').value=lastDate;return}activeDateFilter=next;activeTagFilter='全部';document.querySelectorAll('[data-filter-tag]').forEach(x=>x.classList.toggle('active',x.dataset.filterTag==='全部'));$('entryDate').value=next;const existing=entries.find(e=>e.date===next);if(existing)loadEntry(existing.id);else{lastDate=next;clearForm();restoreDraft(next);renderHistory($('search').value)}renderCalendar()}
function renderHistory(filter=''){const list=$('history');const found=entries.filter(e=>{const matchesText=`${e.event} ${e.lesson} ${e.tags.join(' ')}`.toLowerCase().includes(filter.toLowerCase());const matchesDate=!activeDateFilter||e.date===activeDateFilter;const matchesTag=activeTagFilter==='全部'||(activeTagFilter==='暂无标签'?!e.tags.length:e.tags.includes(activeTagFilter));return matchesText&&matchesDate&&matchesTag});$('activeFilter').textContent=`${activeDateFilter?`${activeDateFilter} · `:'全部日期'}${activeTagFilter==='全部'?'':` · ${activeTagFilter}`}`;if(!found.length){list.innerHTML='<div class="empty"><b>○</b><p>这里还没有复盘<br><small>换个日期或标签看看。</small></p></div>';return}list.innerHTML=found.map(e=>{const d=prettyDate(e.date);return `<article class="history-item" data-id="${e.id}"><div class="history-date"><strong>${d.day}</strong>${d.month} · 周${d.week}</div><div><div class="history-title">${escapeHTML(e.event||'未命名记录')}</div><div class="history-meta">${e.tags.length?e.tags.join(' · '):'暂无标签'}</div></div></article>`}).join('');list.querySelectorAll('.history-item').forEach(el=>el.addEventListener('click',()=>loadEntry(el.dataset.id)))}
function renderQuality(){const counts=Object.fromEntries(qualities.map(q=>[q,0]));entries.forEach(e=>e.tags.forEach(t=>{if(counts[t]!==undefined)counts[t]++}));$('qualityTotal').textContent=`${qualities.filter(q=>counts[q]>0).length} / 5`;$('qualityBars').innerHTML=qualities.map(q=>`<div class="quality-bar ${counts[q]?'filled':''}" title="${q}：${counts[q]}篇"></div>`).join('');const top=qualities.reduce((best,q)=>counts[q]>counts[best]?q:best,qualities[0]);$('qualityTitle').textContent=counts[top]?`正在练习「${top}」 · ${counts[top]}篇`:'五种品质，慢慢成为你'}
function clearForm(){fields.forEach(id=>$(id).value='');selectedTags=[];editingId=null;document.querySelectorAll('#tags button').forEach(b=>b.classList.remove('active'));dirty=false;localStorage.removeItem(`${DRAFT_KEY}-${$('entryDate').value}`);$('saveEntry').firstChild.textContent='收好今天 ';$('saveHint').textContent='所有内容会自动保存在本机'}
function snapshot(){return {date:$('entryDate').value,...Object.fromEntries(fields.map(id=>[id,$(id).value])),tags:[...selectedTags]}}
function restoreDraft(date){const draft=read(`${DRAFT_KEY}-${date}`);if(!draft||!draft.event)return false;fields.forEach(id=>$(id).value=draft[id]||'');selectedTags=draft.tags||[];document.querySelectorAll('#tags button').forEach(b=>b.classList.toggle('active',selectedTags.includes(b.dataset.tag)));$('saveHint').textContent='已恢复未完成草稿';dirty=true;return true}
function loadEntry(id){const e=entries.find(x=>x.id===id);if(!e)return;$('entryDate').value=e.date;activeDateFilter=e.date;renderHistory($('search').value);renderCalendar();fields.forEach(id=>$(id).value=e[id]||'');selectedTags=e.tags||[];editingId=e.id;document.querySelectorAll('#tags button').forEach(b=>b.classList.toggle('active',selectedTags.includes(b.dataset.tag)));$('saveEntry').firstChild.textContent='更新这条 ';$('saveHint').textContent='正在查看历史记录';dirty=false;lastDate=e.date;window.scrollTo({top:0,behavior:'smooth'});showToast('已载入这篇复盘')}
function saveDraft(){const date=$('entryDate').value;if(!date||!fields.some(id=>$(id).value.trim())&&!selectedTags.length)return;localStorage.setItem(`${DRAFT_KEY}-${date}`,JSON.stringify(snapshot()));$('saveHint').textContent='草稿已自动保存';}
function save(){const date=$('entryDate').value,event=$('event').value.trim();if(!date){showToast('请先选择日期');return}if(!event){$('event').focus();showToast('先记下最值得记录的那件事');return}const item={id:editingId||Date.now().toString(),date,event,...Object.fromEntries(fields.slice(1).map(id=>[id,$(id).value.trim()])),tags:[...selectedTags]};if(editingId){entries=entries.map(e=>e.id===editingId?item:e)}else{entries=[item,...entries]}localStorage.setItem(KEY,JSON.stringify(entries));localStorage.removeItem(`${DRAFT_KEY}-${date}`);activeDateFilter=date;renderHistory($('search').value);renderCalendar();renderQuality();$('entryCount').textContent=`${entries.length} 篇`;$('saveHint').textContent='刚刚保存 · 你已经认真看见了今天';dirty=false;editingId=item.id;$('saveEntry').firstChild.textContent='更新这条 ';showToast('这段经历，已经替你收好');}
function showToast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function exportData(){if(!entries.length){showToast('还没有可导出的记录');return}const blob=new Blob([JSON.stringify(entries,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`拾光-复盘-${localDate()}.json`;a.click();URL.revokeObjectURL(url)}
function openAll(){const c=$('allEntries');c.innerHTML=entries.length?entries.map(e=>`<article class="archive-entry"><div class="archive-entry-head">${e.date}<span>${e.tags.join(' · ')||'未分类'}</span></div><h4>${escapeHTML(e.event)}</h4><p>${escapeHTML(e.lesson||'还没有写下经验')}</p></article>`).join(''):'<div class="empty">还没有复盘。</div>';$('allDialog').showModal()}
function setupReminder(){const s=JSON.parse(localStorage.getItem(SETTINGS)||'{"enabled":false,"time":"21:30"}');$('reminderEnabled').checked=s.enabled;$('reminderTime').value=s.time||'21:30';checkReminder();}
function checkReminder(){const s=JSON.parse(localStorage.getItem(SETTINGS)||'{"enabled":false}');if(!s.enabled||!('Notification'in window)||Notification.permission!=='granted')return;const now=new Date(),today=localDate(now),stamp=`${today} ${s.time}`;if(`${today} ${String(now.getHours()).padStart(2,'0')}:${String(now.getMinutes()).padStart(2,'0')}`===stamp&&localStorage.getItem('shiguang-last-notified')!==stamp){new Notification('拾光 · 日复盘',{body:'给今天留几分钟，写下你想记住的事。'});localStorage.setItem('shiguang-last-notified',stamp)}}
$('entryDate').value=localDate();lastDate=$('entryDate').value;setTodayLabel();$('entryCount').textContent=`${entries.length} 篇`;renderCalendar();renderHistory();renderQuality();restoreDraft(lastDate);setupReminder();setInterval(checkReminder,30000);
document.querySelectorAll('#tags button').forEach(b=>b.addEventListener('click',()=>{const t=b.dataset.tag;selectedTags=selectedTags.includes(t)?selectedTags.filter(x=>x!==t):[...selectedTags,t];b.classList.toggle('active');dirty=true;clearTimeout(window.draftTimer);window.draftTimer=setTimeout(saveDraft,600)}));
$('entryDate').addEventListener('change',()=>selectDate($('entryDate').value));$('prevMonth').addEventListener('click',()=>{viewMonth.setMonth(viewMonth.getMonth()-1);renderCalendar()});$('nextMonth').addEventListener('click',()=>{viewMonth.setMonth(viewMonth.getMonth()+1);renderCalendar()});$('newEntry').addEventListener('click',()=>{if(dirty&&!confirm('这篇复盘还没有收好，要先放弃它吗？'))return;clearForm();lastDate=$('entryDate').value;showToast('可以写下今天的另一件事了')});$('saveEntry').addEventListener('click',save);$('search').addEventListener('input',e=>renderHistory(e.target.value));$('showAll').addEventListener('click',openAll);$('allClose').addEventListener('click',()=>$('allDialog').close());$('nextPrompt').addEventListener('click',()=>{currentPrompt=(currentPrompt+1)%prompts.length;$('prompt').textContent=prompts[currentPrompt]});
document.querySelectorAll('[data-filter-tag]').forEach(b=>b.addEventListener('click',()=>{activeTagFilter=b.dataset.filterTag;activeDateFilter='';document.querySelectorAll('[data-filter-tag]').forEach(x=>x.classList.toggle('active',x===b));renderHistory($('search').value);renderCalendar()}));
fields.forEach(id=>$(id).addEventListener('input',()=>{dirty=true;clearTimeout(window.draftTimer);window.draftTimer=setTimeout(saveDraft,600)}));
$('reminderOpen').addEventListener('click',()=>$('reminderDialog').showModal());$('reminderClose').addEventListener('click',()=>$('reminderDialog').close());$('reminderSave').addEventListener('click',async()=>{const enabled=$('reminderEnabled').checked,time=$('reminderTime').value;localStorage.setItem(SETTINGS,JSON.stringify({enabled,time}));if(enabled&&'Notification'in window&&Notification.permission==='default'){await Notification.requestPermission()}$('notifyHint').textContent=enabled?'提醒已设置。请保持此页面在浏览器中打开。':'提醒已关闭。';$('reminderDialog').close();showToast(enabled?'每日提醒已设置':'每日提醒已关闭')});
